---
title: "Tear and Serum IgG Autoantibodies - NOR mice"
author: "ShrutiSinghKakan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	root.dir = '~/Documents/3_Parkinsons_disease/Autoantibody_Data/'
)
library(car)
library(lsmeans)
library(calibrate)
library(dplyr)
#library(DEGreport)
library(DESeq2)
library(DEFormats)
library(edgeR)
library(ggpubr)
library(ggsci)
library(ggplot2)
library(gridExtra)
library(pheatmap)
library(reshape2)
library(RColorBrewer)
library(scales)
library(rstatix)
library(tidyr)
library(magrittr)
#library(PCAtools)
library(tidyverse)
library(Biobase)
#library(marray)
library(limma)
library(gplots)

library(devtools)
#install_github("dpgaile/AutoAntArrayExmpl")
library(AutoAntArrayExmpl)

library(devtools)
#install_github("dpgaile/AutoAntArrayExmpl")
#devtools::install_github('renozao/NMF@devel')
library(AutoAntArrayExmpl)
library(NMF)
library(quantreg)
library(asbio)
library(fdrtool)
#library(discreteMTP)
library(scales)
library(ggsci)
library(ggplot2)

```

#### Loading Raw datasets and creating meta-data df
```{r}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	root.dir = '~/Documents/3_Parkinsons_disease/Autoantibody_Data/'
)
IgG_NSI <- read.csv("~/Documents/3_Parkinsons_disease/Autoantibody_Data/Tear_Autoantibodies_2021/IgG_MCF_SH_292_NSI_nor.csv",  header=T, row.names = 1)[1:120,1:15]
IgG_SNR <- read.csv("~/Documents/3_Parkinsons_disease/Autoantibody_Data/Tear_Autoantibodies_2021/IgG_MCF_SH_292_SNR.csv",  header=T, row.names = 1)[1:120,1:15]
IgG_SNR$average <- rowMeans(IgG_SNR)
IgG_SNR$med <- rowMedians(as.matrix(IgG_SNR))
IgG_NSI <- IgG_NSI[which(IgG_SNR$med>3),]
IgG_SNR <- IgG_SNR[which(IgG_SNR$med>3),]
IgG_raw=list()
IgG_raw$NSI <- as.matrix(IgG_NSI)
IgG_raw$SNR <- as.matrix(IgG_SNR)[,1:15]

Strain <- c(rep(c("NOR", "BALBc"), each=3), rep(c("NOR"), each=6), rep(c("BALBc"), each=3))
Biofluid <- c(rep("Tears",6), rep("Serum", 9))
colData <- as.data.frame(cbind(c(colnames(IgG_NSI)), Strain, Biofluid))
colnames(colData) <- c('Sample', "Strain", "Biofluid")
rownames(colData) <- colData$Sample

colData$Strain <- factor(colData$Strain)
colData$Strain <- relevel(colData$Strain, ref = "BALBc")
colData$Biofluid <- factor(colData$Biofluid, levels = c("Tears", "Serum"))

```

#Normalization
```{r}
IgG_SNR$average <- rowMeans(IgG_SNR)
IgG_SNR$med <- rowMedians(as.matrix(IgG_SNR))
IgG_NSI <- IgG_NSI[which(IgG_SNR$med>3),]
IgG_SNR <- IgG_SNR[which(IgG_SNR$med>3),]

IgG_raw=list()
IgG_raw$NSI <- as.matrix(IgG_NSI)
IgG_raw$SNR <- as.matrix(IgG_SNR)
IgG_raw$SInfo <- colData

clrs=c(rep(pal_jco("default")(4)[1:2], each=3), rep(pal_jco("default")(4)[3], each=6), rep(pal_jco("default")(4)[4], each=3))
pchs=c(rep(2,3),rep(4,3), rep(5,6), rep(8,3))

#Centering and Scaling Differences Across Features
# Tukey Tri-mean for location
TriMnG=RowTriMeans(IgG_raw$NSI) # 99 elements (same as num of rows in NSI)
# Biweight midvariance for spread
bw.estG=unlist(apply(IgG_raw$NSI,1,r.bw)) # 99 elements

```

## Normalization
### First Stage

```{r}
#enable to background correct
IgG_raw$NSI <- as.matrix(IgG_NSI)
IgG_raw$NSI = IgG_raw$NSI*IgG_raw$SNR[,1:15] ##NSI changed permanantly
IgG_raw$X_norm_1=IgG_raw$NSI
eps=.10
IgG_raw$QregFits=array(NA,dim=c(99,2))
TriMn=RowTriMeans(IgG_raw$X_norm_1) #new NSI Tukey tri mean
ResMat=c(IgG_raw$X_norm_1,IgG_raw$X_norm_1)-matrix(rep(TriMn,30),ncol=30) #New_NSI - NewNSI_TriMn 
SubMat=abs(ResMat)<quantile(as.vector(abs(ResMat)),prob=1-eps)

par(mfrow=c(2,2));par(mgp=c(1.5,.5,0));par(mar=c(2.75,2.75,1.5,0.25))
plot(rep(TriMn,30),as.vector(ResMat),
     xlim=quantile(TriMn,prob=c(0,.8)),
     ylim=quantile(as.vector(ResMat),prob=c(0.05,.95)),
     type="n",xlab="Raw Signal Tri-Mean",ylab="Raw Signal",
     main="IgG Raw Signal")
for(j in 1:15){
   points(TriMn,ResMat[,j],cex=0.5,pch=pchs[j],col=clrs[j])
   points(TriMn,ResMat[,15+j],cex=0.5,pch=pchs[j],col=clrs[j])
   y=c(ResMat[,j], ResMat[,15+j])
   x=c(TriMn, TriMn)
   fitj <- rq(y ~ x, tau = .5,subset=which(c(SubMat[,j], SubMat[,15+j])))
   abline(coef(fitj),col=clrs[j])
   IgG_raw$QregFits[j,]=coef(fitj)
   prdct=coef(fitj)[1]+coef(fitj)[2]*TriMn
   IgG_raw$X_norm_1[,j]=IgG_raw$X_norm_1[,j]-prdct
} ###substracting the model fit straight line from the data
#Xnorm_1 here is the residual value

```


```{r}
eps=0.10
q.eps=0.10
lambda=.10 # incremental change
nitr=75 # number of iterations -> this should help us optimize the lambda for best fit
sad=rep(0,nitr) # sum of absolute deviations
# re-init
IgG_raw$X_1step_norm_1=IgG_raw$X_norm_1 #calculated in the last loop
IgG_raw$X_norm_1=IgG_raw$NSI #reinitializing


for(i in 1:nitr){
   # snoop and grab invariants
   X=IgG_raw$X_norm_1
   iWRS=function(i) t.test(X[i,c(1:3,7:12)],X[i,c(4:5,13:15)])$p.value
   qMat=matrix(rep(mapply(iWRS,1:99),30),ncol=30)
   qMat[which(is.na(qMat[,1])==T),] <- 0 #all NANs replaced by 0
   qcut=quantile(qMat[,1],prob=q.eps)
   
   TriMn=RowTriMeans(IgG_raw$X_norm_1)
   ResMat=c(IgG_raw$X_norm_1,IgG_raw$X_norm_1)-matrix(rep(TriMn,30),ncol=30)
   SubMat=abs(ResMat)<quantile(as.vector(abs(ResMat)),prob=1-eps) #all residuals with absolute values less than the cutoff of 90%
   SubMat[qMat<qcut]=FALSE #which p values are greater than the cutoffs
   for(j in 1:15){
      y=c(ResMat[,j], ResMat[,15+j])
      x=c(TriMn, TriMn)
      fitj <- rq(y ~ x, tau = .5,subset=which(c(SubMat[,j], SubMat[,15+j])))
      prdct=coef(fitj)[1]+coef(fitj)[2]*TriMn
      IgG_raw$X_norm_1[,j]=IgG_raw$X_norm_1[,j]-lambda*prdct
      sad[i]=sad[i]+sum(abs(2*lambda*prdct))
   }###substracting the model fit straight line from the data
   print(sad)
   print(qcut)
}

plot(1:nitr,sad,main="iterative adj IgG")
smoothScatter(IgG_raw$X_1step_norm_1,IgG_raw$X_norm_1, nbin = 500)
abline(0,1,col="steelblue")

```

### Second Stage ########
```{r}
deltaG=min(as.vector(IgG_raw$X_norm_1))
IgG_raw$W_1=log(IgG_raw$X_norm_1-deltaG+1)
# get resids..
W_1=IgG_raw$W_1
RW=RowTriMeans(W_1)
# get residual matrices
RW_MAT=matrix(rep(RW,dim(W_1)[2]),ncol=dim(W_1)[2])
W_1=W_1-RW_MAT

W=W_1
bw.est=unlist(apply(W,2,r.bw))
# now, rescale
for(j in 1:15){
   W_1[,j]=W_1[,j]/sqrt(bw.est[j])
}
# now, get new values..
IgG_raw$W_1=RW_MAT+W_1

```

## Formal Comparison of NOR and Balb/c AutoAntigen Expresion Profiles

```{r}
mydata <- as.matrix(IgG_raw$W_1)
#mydata <- as.matrix(IgG_raw$X_nrm_1)
colData$Strain <- relevel(colData$Strain, ref = "BALBc")
colData$Biofluid <- factor(colData$Biofluid)

conditions<- paste(colData$Strain, colData$Biofluid,sep=".")
conditions <- factor(conditions, levels=unique(conditions))
design <- model.matrix(~0+ conditions)
rownames(design) <- colnames(mydata)
colnames(design) <- levels(conditions)
fit <- lmFit(mydata, design)
#sqrt(anova.MAList(fit)["Residuals","Mean Sq"]) #???
summary(fit)

cont.matrix<- makeContrasts(
   NTvsBT =  NOR.Tears - BALBc.Tears,
   NSvBS = NOR.Serum - BALBc.Serum,
   NTvNS = NOR.Tears - NOR.Serum,
   levels = design)

fit.cont<- contrasts.fit(fit, cont.matrix)
fit.cont<- eBayes(fit.cont)
qqt(fit.cont$t,df=fit.cont$df.prior+fit.cont$df.residual,cex=1)
abline(0,2)
topTable(fit.cont,number=23,adjust="BH")

```

#R-Squared ....... Checking goodness of fit
```{r}
for (i in 1:99){
   sst <- rowSums(mydata^2)
   ssr <- sst - fit.cont$df.residual*(fit.cont$sigma^2)
   Rsq<- (ssr/sst)
}
plot(1:99, Rsq)
which(Rsq<0.7)

summary(fit.cont$r.squared)
```

#Deciding 
```{r}

decide <- matrix(c("fdr",0.05,
                   "fdr",0.1, "none",0.005, "none", 0.01),nrow=4,ncol=2,byr=T)
# initialize:
mysum <- as.list(1:nrow(decide))
mynum <- 0
maxmax <- 0
for (test in 1:nrow(decide)){
   results<-decideTests(fit.cont,
                        adjust.method=decide[test,1],
                        p=as.numeric(decide[test,2]))
   summary(results) -> mysum[[test]]
   mynum[test] <-length(which(apply(results,1,function(x)any(x,na.rm=T))))
   maxmax <- max(c(maxmax, as.vector(mysum[[test]][c(1,3),])))
}
par(mfrow=c(1,nrow(decide)))
for (test in 1:nrow(decide))
{
   as.numeric(as.vector(mysum[[test]][3,]))->plotMe1
   as.numeric(as.vector(mysum[[test]][1,]))->plotMe2
   maxData = max(plotMe1)
   maxData2 = max(plotMe2)
   barplot(plotMe1,horiz=T,col="red",xlim=c(-maxmax,maxmax),
           main=paste("Gene Changes \np<",decide[test,2], ", " , decide[test,1],
                      " (" ,mynum[test] ,")",sep=""))->yy
   barplot(-plotMe2,horiz=T,col="green",add=T)->yy
   xx<-vector("integer",ncol(mysum[[test]]))
   text(xx,yy,colnames(mysum[[test]]))
   text((plotMe1+10)*0 + .9*maxData,yy+0.1,format(plotMe1,digits=3))
   text((-plotMe2-10)*0 - .9*maxData2,yy+0.1,format(plotMe2,digits=3))
}
```

#Generate outputs for IgG Datasets
```{r}

results<-decideTests(fit.cont,adjust.method="none", p=0.01)
summary(results)
write.fit(fit.cont,file="~/Documents/3_Parkinsons_disease/Autoantibody_Data/Tear_Autoantibodies_2021/IgG_DGE_W1_results.csv",adjust="none",results=results, sep=',')
fitObj <- read.csv("~/Documents/3_Parkinsons_disease/Autoantibody_Data/Tear_Autoantibodies_2021/IgG_DGE_W1.csv", header=T, row.names = 1)

myNames<-names(fitObj)
res.col<- which(regexpr("Res.",myNames)>0)
DElist<- which(apply(fitObj[,res.col],1,function(x)any(x,na.rm=T)))
length(DElist)

fitObjDE <-fitObj[DElist,]
fitObjDE$Autoantigen <- rownames(fitObjDE)
```

#Generating Boxplots for Serum hits
```{r}
fitObjres<- fitObj[which(fitObj$P.value.NSvBS < 0.05 & abs(fitObj$Coef.NSvBS) > 0.5), ]#Serum
mydata <- as.matrix(IgG_raw$W_1)[1:99,]
hits <- rownames(fitObjres)
chart_design <- theme(
   plot.title = element_text(color = "Black", size = 17, face = "bold", margin = margin(b=25), hjust=0.4),
   axis.text.x = element_text(size=15),
   axis.text.y = element_text(size=14),
   axis.title.x = element_blank(),
   legend.text = element_blank(),
   legend.title = element_blank(),
   legend.position = "",
   axis.title.y = element_text(size=15, margin = margin(r = 5)),
   strip.text.x = element_text(size =17, margin = margin(b=25), face='bold', hjust=0.4),
   strip.background = element_blank(), 
   strip.placement = "outside")

Y=matrix(nrow=length(hits),ncol=15)
for (i in 1:length(hits)) {
   Y[i,] <- mydata[hits[i],]
}

rownames(Y) <- hits
colnames(Y) <- colData$Sample

Y <- as.data.frame(t(Y))
Y$Strain <- colData$Strain
Y$Biofluid <- colData$Biofluid
hits <- colnames(Y)[1:29]
Y_Ser <- Y[which(Y$Biofluid=="Serum"),]

colnames(Y_Ser)[10] <- "La SSB"
colnames(Y_Ser)[18] <- "PM Scl100"
colnames(Y_Ser)[20] <- "Sm RNP"
colnames(Y_Ser)[22] <- "TNF alpha"
colnames(Y_Ser)[23] <- "U1-snRNP 68 70"



```


```{r}

```


```{r}

```

