---
title: "Serum_Autoantibody_2021"
knit: (function(input_file, encoding) {
    out_dir <- 'docs';
    rmarkdown::render(input_file,
      encoding=encoding,
      output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "ShrutiSinghKakan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Loading the libraries, message=FALSE, warning=FALSE}

library(car)
library(lsmeans)
library(calibrate)
library(dplyr)
#library(DEGreport)
library(DESeq2)
library(DEFormats)
library(edgeR)
library(emmeans)
library(ggpubr)
library(ggsci)
library(ggplot2)
library(gridExtra)
library(pheatmap)
library(reshape2)
library(RColorBrewer)
library(scales)
library(rstatix)
library(tidyr)
library(magrittr)
library(PCAtools)
library(tidyverse)
library(Biobase)
library(marray)
library(limma)
library(gplots)
```

##### 0 Dataset ######
```{r Dataset}
data <- read.csv("../../SerumAntibodies_2021/IgG_MCF_SH_179_raw.csv",  header=T, row.names = 1)
#Columns 16-47 are empty and are therefore removed
data <- as.data.frame((data))[,-c(16:47)]

#Creating metadata including Strain and age
Strain <- c(rep(c("BALBc", "NOD"), each=6), rep(c("NOD"), each=3))
Age <- c(rep(c("8wks", "28wks"), each=3), rep(c("8wks", "24wks", "33wks"), each=3))
Group <- c(rep(c("A","B","C","D","E"), each=3))
colData <- as.data.frame(cbind(c('B1_8', 'B2_8', 'B3_8', 'B1_28', 'B2_28', 'B3_28', 'N1_8', 'N2_8', 'N3_8', 'N1_24', 'N2_24', 'N3_24', 'N1_33', 'N2_33', 'N3_33'), Strain, Age, Group))
colnames(colData) <- c('Sample', "Strain", "Age", "Group")
rownames(colData) <- colData$Sample
colnames(data) <- colData$Sample

colData$Strain <- factor(colData$Strain)
colData$Strain <- relevel(colData$Strain, ref = "BALBc")
colData$Age <- factor(colData$Age, levels = c("8wks", "24wks", "28wks", "33wks"))
colData$Age <- relevel(colData$Age, ref='8wks')

```

###### 1 Visualizing raw data ###########
```{r Visualization}
#Boxplot of raw Signal Distribution, not normalized

mydata<-as.matrix(log2(data+0.5))

boxplot(as.data.frame(mydata),main="Signal distribution, Not normalized",xlab="Samples",ylab="Log2 Intensity",cex=0.8)


```

######2 Clustering samples based on Pearson correlation ############

```{r Sample Clustering}
matcor<-cor(mydata)
range(as.vector(matcor))

strain<-as.character(as.numeric(colData$Strain))
age<-as.character(as.numeric(colData$Age))

library(gplots)
heatmap.2(matcor,trace="none",col=heat.colors(40),ColSideColors=strain,
          RowSideColors=age, cexCol=1,cexRow=1,labCol="")
```

###### 3 Data filtering and Normalization ########
```{r Data filtering, Log2 Data normalization and visualization}
mydata <- as.matrix((data))
dataN <- (mydata[1:95,]/mydata[96,] * 100) #df with all rows
dataN <- mydata
boxplot(as.data.frame(log2(dataN+0.5)),main="Signal distribution, Not normalized",xlab="Samples",ylab="Log2 Intensity",cex=0.8)

library(matrixStats) #for function rowmedians
IgG_SNR <- read.csv("../../SerumAntibodies_2021/IgG_MCF_SNR.csv",  header=T, row.names = 1)[,1:15]
IgG_SNR$average <- rowMeans(IgG_SNR)
IgG_SNR$med <- rowMedians(as.matrix(IgG_SNR))
mydata <- data[which(IgG_SNR$average>3),] #filtering rows with high noise (i.e., rows with Signal to Noise Ratio or SNR > 3)
mydata<-as.matrix(mydata)
dataN <- mydata
boxplot(as.data.frame(log2(dataN+0.5)),main="Signal distribution, Not normalized SNR>3",xlab="Samples",ylab="Log2 Intensity",cex=0.8)

dataN <- (mydata[1:69,]/mydata[70,]) * 100000
boxplot(as.data.frame(log10(dataN+0.5)),main="IgG normalization",col=strain)

library(limma) #for function plotMDS
plotMDS(log2(dataN+0.5))
mm <- model.matrix(~0 + Group)
y <- voom((dataN), mm, plot = T)

countData = as.data.frame(dataN)

df_dseq = melt(countData, variable.name = "Samples", value.name = "count") # reshape the matrix 
df_dseq = data.frame(df_dseq, Condition = substr(df_dseq$Samples,1,1))
mycolors <- colorRampPalette(brewer.pal(8, "Set1"))(13)

ggplot(df_dseq, aes(x = log10(count+0.5), colour = Samples, fill = Samples)) + 
   geom_density(alpha = 0, size = 0.8) + 
   facet_wrap(~Condition, ncol=3) #+
   #theme_minimal() + xlim(-1.5,6) +
   #scale_colour_manual(values=mycolors, name="") + guides(fill="none")
```


```{r}
matcor<-cor(dataN)
range(as.vector(matcor))
strain<-as.character(as.numeric(colData$Strain))
age<-as.character(as.numeric(colData$Age))
heatmap.2(matcor,trace="none",col=heat.colors(40),ColSideColors=strain,RowSideColors=age, cexCol=1,cexRow=1,labCol="")
```

###### 4 DGE analysis ##########
```{r DGE using Limma lmFit}
#mydata <- as.matrix((data+0.5))

conditions<- paste(colData$Strain[1:12], colData$Age[1:12],sep=".")

conditions <- factor(conditions, levels=unique(conditions))
design <- model.matrix(~0+ conditions)
colnames(design) <- levels(conditions)

#contrasts of the previous analysis. 
#cont.matrix<- makeContrasts(B8vsN8 = NOD.8wks - BALBc.8wks, B28vN24 = NOD.24wks - BALBc.28wks,
#   B28vN33 = NOD.33wks - BALBc.28wks,
#   N24vN8 = NOD.24wks - NOD.8wks,
#   N33vN8 = NOD.33wks - NOD.8wks,
#   N33vN24 = NOD.33wks - NOD.24wks,
#   levels = design)
#Introducing new contrasts by removing the 33 week old samples.
fit <- lmFit(dataN[,1:12], design)
cont.matrix<- makeContrasts(
B8vsN8 = NOD.8wks - BALBc.8wks,
B28vN24 = NOD.24wks - BALBc.28wks,
N24vN8 = NOD.24wks - NOD.8wks,
B28vB8 = BALBc.28wks - BALBc.8wks,
levels = design)

fit.cont<- contrasts.fit(fit, cont.matrix)
fit.cont<- eBayes(fit.cont)

decide <- matrix(c("fdr",0.05,
                   "fdr",0.1, "none",0.005, "none", 0.01),nrow=4,ncol=2,byr=T)

mysum <- as.list(1:nrow(decide))
mynum <- 0
maxmax <- 0
for (test in 1:nrow(decide)){
   results<-decideTests(fit.cont,
                        adjust.method=decide[test,1],
                        p=as.numeric(decide[test,2]))
   summary(results) -> mysum[[test]]
   mynum[test] <-length(which(apply(results,1,function(x)any(x,na.rm=T))))
   maxmax <- max(c(maxmax, as.vector(mysum[[test]][c(1,3),])))
}
par(mfrow=c(1,nrow(decide)))
for (test in 1:nrow(decide))
   {
   as.numeric(as.vector(mysum[[test]][3,]))->plotMe1
   as.numeric(as.vector(mysum[[test]][1,]))->plotMe2
   maxData = max(plotMe1)
   maxData2 = max(plotMe2)
   barplot(plotMe1,horiz=T,col="red",xlim=c(-maxmax,maxmax),
           main=paste("Gene Changes \np<",decide[test,2], ", " , decide[test,1],
                      " (" ,mynum[test] ,")",sep=""))->yy
   barplot(-plotMe2,horiz=T,col="green",add=T)->yy
   xx<-vector("integer",ncol(mysum[[test]]))
   text(xx,yy,colnames(mysum[[test]]))
   text((plotMe1+10)*0 + .9*maxData,yy+0.1,format(plotMe1,digits=3))
   text((-plotMe2-10)*0 - .9*maxData2,yy+0.1,format(plotMe2,digits=3))
}
```


```{r DGE Results using Limma}
results<-decideTests(fit.cont,adjust.method="none", p=0.01)
summary(results)
write.fit(fit.cont,file="IgG_DGE_0423.csv",adjust="none",results=results, sep=',')
fitObj <- read.csv("IgG_DGE_0423.csv", header=T, row.names = 1)

toptable1 <- topTable(fit.cont, coef=2, adjust.method="none", p=0.01, sort.by = "P", n = Inf)
write.csv(toptable1,file="IgG_DGE_0423_II.csv")

myNames<-names(fitObj)
res.col<- which(regexpr("Res.",myNames)>0)
DElist<- which(apply(fitObj[,res.col],1,function(x)any(x,na.rm=T)))
length(DElist)

fitObjDE <-fitObj[DElist,]

fitObjDE$Autoantigen <- rownames(fitObjDE)
fitObjDE

```


```{r}
library(devtools)
install_github("dpgaile/AutoAntArrayExmpl")
library(AutoAntArrayExmpl)

library(devtools)
install_github("dpgaile/AutoAntArrayExmpl")
library(AutoAntArrayExmpl)
library(NMF)
library(quantreg)
library(asbio)
library(fdrtool)
library(discreteMTP)
```

#Sample Spot and Background Distributions
```{r}
IgG_NSI <- read.csv("../../SerumAntibodies_2021/IgG_MCF_NSI.csv",  header=T, row.names = 1)[1:96,1:12]
IgG_SNR <- read.csv("../../SerumAntibodies_2021/IgG_MCF_SNR.csv",  header=T, row.names = 1)[1:96,1:12]
Strain <- c(rep(c("BALBc", "NOD"), each=6))
Age <- c(rep(c("8wks", "28wks"), each=3), rep(c("8wks", "24wks"), each=3))
Group <- c(rep(c("A","B","C","D"), each=3))
colData <- as.data.frame(cbind(c('B1_8', 'B2_8', 'B3_8', 'B1_28', 'B2_28', 'B3_28', 'N1_8', 'N2_8', 'N3_8', 'N1_24', 'N2_24', 'N3_24'), Strain, Age, Group))
colnames(colData) <- c('Sample', "Strain", "Age", "Group")
rownames(colData) <- colData$Sample
colnames(IgG_NSI) <- colData$Sample
colnames(IgG_SNR) <- colData$Sample

colData$Strain <- factor(colData$Strain)
colData$Strain <- relevel(colData$Strain, ref = "BALBc")
colData$Age <- factor(colData$Age)
colData$Age <- relevel(colData$Age, ref='8wks')

```

######Data Filtering #######
```{r}
colData <- colData[1:12,] #remove the last group - M NOD 33 wks
IgG_SNR$average <- rowMeans(IgG_SNR)
IgG_SNR$med <- rowMedians(as.matrix(IgG_SNR))
IgG_NSI <- IgG_NSI[which(IgG_SNR$average>3),] #filtering rows with high noise (i.e., rows with SNR > 3)
IgG_SNR <- IgG_SNR[which(IgG_SNR$average>3),]
IgG_raw=list()
IgG_raw$NSI <- as.matrix(IgG_NSI)
IgG_raw$SNR <- as.matrix(IgG_SNR)[,1:12]
IgG_raw$SInfo <- colData

clrs=c(rep(pal_jco("default")(5), each=3))[1:12]
pchs=c(rep(3,3),rep(4,3), rep(5,3), rep(6,3), rep(7,3))[1:12]

tiff("fig1_.tiff", units="in", width=7, height=7.4, res=300)
par(mfrow=c(2,2));par(mgp=c(1.5,.5,0));par(mar=c(2.75,2.75,1.5,0.25))
plot(as.vector(IgG_raw$NSI),as.vector(IgG_raw$SNR),type="n",ylab="IgG Background Intensity (SNR)",xlab="IgG Spot Intensity (NSI)" )
abline(0,1,lwd=3,col="steelblue")
for(j in 1:12) points(IgG_raw$NSI[,j],col=clrs[j],IgG_raw$SNR[,j], pch=j,cex=0.5)
plot(log(as.vector(IgG_raw$NSI)),
     log(as.vector(IgG_raw$SNR)),
     type="n",ylab="log IgG Background Intensity (SNR)",xlab="log IgG Spot Intensity (NSI)")
abline(0,1, lwd=3,col="steelblue")
for(j in 1:12) points(log(IgG_raw$NSI[,j]),log(IgG_raw$SNR[,j]),
                      pch=j,col=clrs[j],cex=0.5)
legend(6.5,0,lty=1,lwd=3,col=clrs[c(1,4,7,11)],pch=pchs[c(1,4,7,11)],legend=c(paste(rep("B",2),rep(c(8,28), each=1)), paste(rep("N",2),rep(c(8,24), each=1))),bty="n",ncol=1)

plot(density(log10(IgG_raw$NSI[,1]+ 0.5),type="l"), main="  log10(NSI +0.5)", sub=" . ")
for(j in 2:12) {
   dens<-density(log10(IgG_raw$NSI[,j]+0.5))
   lines(dens, cex=0.5,pch=pchs[j],col=clrs[j],cex.main=1)
}

legend(-0.8,0.6,lty=1,lwd=3,col=clrs[c(1,4,7,11)],pch=pchs[c(1,4,7,11)],legend=c(paste(rep("B",2),rep(c(8,28), each=1)), paste(rep("N",2),rep(c(8,24), each=1))),bty="n",ncol=1)
plot(density(log10(IgG_raw$NSI[,j]+0.5)), main="log10(SNR +0.5) ", sub=" . ", type="l")
for(j in 1:12) {
   dens<-density(log10(IgG_raw$NSI[,j]+0.5))
   lines(dens, cex=0.5,pch=pchs[j],col=clrs[j],cex.main=1)
}

dev.off()
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```
